version: "3.5"


services:
  #================================
  #      POSTGRESQL DATABASE
  #================================
  pg_master:
    build: ../postgres/master
    hostname: pg-master
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=django-db
      - PG_REP_USER=django_rep
      - PG_REP_PASSWORD=password
    networks:
      - country-django-graphql-example-network
  pg_slave:
    hostname: pg-slave
    build: ../postgres/slave
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=django-db
      - PG_REP_USER=django_rep
      - PG_REP_PASSWORD=password
      - PG_MASTER_HOST=pg-master
    networks:
      - country-django-graphql-example-network

  #================================
  #    POSTGRESQL DATABASE GUI
  #================================
  country-django-graphql-example-postgresql-gui:
    container_name: country-django-graphql-example-postgresql-gui
    image: dpage/pgadmin4
    hostname: country-django-graphql-example-postgresql-gui
    ports:
      - 5050:80
    volumes:
       - ../.data/pgadmin:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - pg_master
    networks:
      - country-django-graphql-example-network
    restart: always

  #================================
  #               REDIS
  #================================
  country-django-graphql-example-redis:
    container_name: country-django-graphql-example-redis
    image: redis:alpine
    hostname: country-django-graphql-example-redis
    networks:
      - country-django-graphql-example-network
    restart: always

#================================
#         NETWORK
#================================
networks:
  country-django-graphql-example-network:
    external:
      name: country-django-graphql-example-network
